### ISSUE TITLE
More than 2 segments of a parameter

### ISSUE THREAD

**Issue by ben-gillott** [cucapra/gator#121]
It would be useful to support up to three parts of a function parameter, for example

void Test(out float varName){
}

**Comment by Checkmate50** [comment]
I think we should specifically add the ability to add "modifiers" to variables, which also includes things like `uniform, attribute, in, intout`, etc..., since these modifiers show up a decent amount in Graphics.  I propose in particular that any modifier can be declared as valid with the syntax: `declare modifier attribute`, for example
